package com.uttt.common;

public enum MessageType {
	//
	PLAYER_TEST_RESPONSE,
	PLATFORM_DISCOVERY_RESPONSE,
	GET_OPEN_GAMES_RESPONSE,
	START_NEW_GAME_RESPONSE,
	JOIN_GAME_RESPONSE,
	
	//
	PLAYER_TEST_REQUEST,
	PLATFORM_DISCOVERY_REQUEST,
	GET_OPEN_GAMES_REQUEST,
	START_NEW_GAME_REQUEST,
	JOIN_GAME_REQUEST,
	
	//
	FAILED;
	
	public final static String API_VERSION = "0.1";
}
